# Digital Business Card - Production

# HTTP to HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name card.sumeetsaini.com;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        return 301 https://card.sumeetsaini.com$request_uri;
    }
}

# Production (HTTPS only)
server {
    listen 443 ssl;
    server_name card.sumeetsaini.com;

    include /etc/nginx/conf.d/common/security.conf;

    ssl_certificate /etc/letsencrypt/live/sumeetsaini.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sumeetsaini.com/privkey.pem;

    location / {
        proxy_pass http://card_sumeetsaini_com_prod;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }
}