# reliq.digital - Production (HTTPS)

server {
    listen 80;
    server_name reliq.digital www.reliq.digital;
    return 301 https://reliq.digital$request_uri;
}

server {
    listen 443 ssl;
    server_name reliq.digital www.reliq.digital;
    
    # security configuration
    include /etc/nginx/conf.d/common/security.conf;
    
    # SSL certificates
    ssl_certificate /etc/letsencrypt/live/reliq.digital/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/reliq.digital/privkey.pem;

    location / {
        proxy_pass http://reliqdigital_prod;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }

    location /stats/ {
        proxy_pass http://plausible_prod/;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }

    location /api/event {
        proxy_pass http://plausible_prod/api/event;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }

    location /vulkan/ {
        valid_referers reliq.digital *.reliq.digital;
        if ($invalid_referer) {
            return 403;
        }
        proxy_pass http://vulkan_api_prod/;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }
}