# ReliqStudios - Production (HTTPS)

server {
    listen 80;
    server_name reliqstudios.com www.reliqstudios.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name reliqstudios.com www.reliqstudios.com;
    
    # security configuration
    include /etc/nginx/conf.d/common/security.conf;
    
    # SSL certificates
    ssl_certificate /etc/letsencrypt/live/reliqstudios.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/reliqstudios.com/privkey.pem;

    location / {
        proxy_pass http://reliqstudios_prod;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }

    location /stats/ {
        proxy_pass http://plausible_prod/;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }

    location /api/event {
        proxy_pass http://plausible_prod/api/event;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }

    location /vulkan/ {
        # Allow only from your own domain (internal access)
        valid_referers reliqstudios.com *.reliqstudios.com;
        if ($invalid_referer) {
            return 403;
        }
        proxy_pass http://vulkan_api_prod/;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }
}
