# Production Upstreams
upstream sumeetsaini_com_prod {
    server sumeetsaini_com:80;
}

upstream vulkan_api_prod {
    server vulkan:3000;
}

upstream arcanecodex_prod {
    server arcanecodex:80;
}

upstream mailcow_nginx {
    server mailcowdockerized-nginx-mailcow-1:8080;
}