# Production Upstreams
upstream sumeetsaini_com_prod {
    server sumeetsaini_com:80;
}

upstream vulkan_api_prod {
    server vulkan:3000;
}

upstream arcanecodex_prod {
    server arcanecodex:80;
}

upstream mailcow_nginx {
    server mailcowdockerized-nginx-mailcow-1:8080;
}

upstream plausible_prod {
    server plausible:8000;
}

upstream ao3_prod {
    server ao3:80;
}

upstream reliqstudios_prod {
    server reliqstudios:80;
}

upstream reliqdigital_prod {
    server reliqdigital:80;
}

upstream reliqlabs_prod {
    server reliqlabs:80;
}

upstream card_sumeetsaini_com_prod {
    server card:3000;
}

upstream babbi_world_prod {
    server babbi_world:80;
}
