# Include upstreams and common configurations
include /etc/nginx/conf.d/prod/upstreams.conf;

# API - Production (HTTPS)
server {
    listen 443 ssl;
    server_name vulkan.sumeetsaini.com;
    
    # security configuration
    include /etc/nginx/conf.d/common/security.conf;
    
    # SSL certificates
    ssl_certificate /etc/letsencrypt/live/vulkan.sumeetsaini.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vulkan.sumeetsaini.com/privkey.pem;
    
    location / {
        proxy_pass http://vulkan_api_prod;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }
}
