# Mailcow Dockerized Integration
# This file integrates the existing mailcow setup with unified orchestration
# Mailcow continues to use host networking for compatibility

# Override specific mailcow services for integration
services:
  nginx-mailcow:
    # Ensure nginx binds to localhost for gateway proxy
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8443:8443"
    # Add dependency on gateway for proper startup order
    depends_on:
      - gateway
    networks:
      - default
      - mailcow-network

# Import mailcow services with network overrides
include:
  - /opt/mailcow-dockerized/docker-compose.yml

networks:
  aether-network:
    external: true