services:
  vulkan:
    build:
      context: ./vulkan
    container_name: vulkan
    restart: always
    environment:
      # From .env file
      - PORT=${VULKAN_PORT}
      - HOST=${VULKAN_HOST}
    ports:
      - "${VULKAN_PORT}:${VULKAN_PORT}"

  sumeetsaini_com:
    build:
      context: ./sumeetsaini_com
    container_name: sumeetsaini_com
    restart: always

  gateway:
    image: nginx:stable-alpine
    container_name: gateway_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sumeetsaini_com
      - vulkan
