# Mailcow Dockerized Integration
# This file integrates the existing mailcow setup with unified orchestration

# Import mailcow services
include:
  - /opt/mailcow-dockerized/docker-compose.yml

# Define additional network for aether integration
networks:
  aether-network:
    external: true