services:
  sumeetsaini_com:
    build:
      dockerfile: Dockerfile.prod
    image: ghcr.io/kungfusaini/sumeetsaini_com:latest
    
  vulkan:
    build:
      dockerfile: Dockerfile.prod
    image: ghcr.io/kungfusaini/vulkan:latest
    environment:
      - NODE_ENV=prod
      - MAIL_ENABLED=true
      - MAILCOW_HOST=mailcowdockerized-postfix-mailcow-1
      - CONTACT_EMAIL=${CONTACT_EMAIL}
    networks:
      - aether-network
      - mailcowdockerized_mailcow-network
      
  gateway:
    image: ghcr.io/kungfusaini/gateway:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./services/gateway/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - ./services/gateway/conf.d:/etc/nginx/conf.d:ro
    networks:
      - aether-network
      - mailcowdockerized_mailcow-network