services:
  sumeetsaini_com:
    build: 
      context: ./services/sumeetsaini_com
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    container_name: sumeetsaini_com
    
  vulkan:
    build:
      context: ./services/vulkan  
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - HOST=0.0.0.0
      - MAIL_ENABLED=false
    restart: unless-stopped
    container_name: vulkan
    
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sumeetsaini_com
      - vulkan
    restart: unless-stopped
    container_name: gateway_nginx

networks:
  default:
    name: aether-network