services:
  sumeetsaini_com:
    build: 
      context: ./services/sumeetsaini_com
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    container_name: sumeetsaini_com
    
  vulkan:
    build:
      context: ./services/vulkan  
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - HOST=0.0.0.0
      - MAIL_ENABLED=true
      - FROM_EMAIL=vulkan@sumeetsaini.com
    restart: unless-stopped
    container_name: vulkan
    
  arcanecodex:
    restart: unless-stopped
    container_name: arcanecodex
    
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    volumes:
      - ./services/gateway/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sumeetsaini_com
      - vulkan
      - arcanecodex
    restart: unless-stopped
    container_name: gateway_nginx

networks:
  default:
    name: aether-network
