services:
  sumeetsaini_com:
    image: ghcr.io/kungfusaini/sumeetsaini_com:latest

  vulkan:
    image: ghcr.io/kungfusaini/vulkan:latest
    environment:
      - NODE_ENV=prod
      - MAIL_ENABLED=true
      - MAILCOW_HOST=mailcowdockerized-postfix-mailcow-1
      - CONTACT_EMAIL=${CONTACT_EMAIL}
    networks:
      - aether-network
      - mailcowdockerized_mailcow-network

  arcanecodex:
    image: ghcr.io/kungfusaini/arcanecodex:latest
    environment:
      - HUGO_ENV=production
      - HUGO_BASEURL=https://arcanecodex.dev/
      - HUGO_ENABLE_ROBOTS=true
    networks:
      - aether-network

  gateway:
    image: ghcr.io/kungfusaini/gateway:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - aether-network
      - mailcowdockerized_mailcow-network
    depends_on:
      - sumeetsaini_com
      - vulkan
      - arcanecodex
      - plausible
