services:
  sumeetsaini_com:
    volumes:
      - ./services/sumeetsaini_com:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=dev
      
  vulkan:
    build:
      context: ./services/vulkan
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/vulkan:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - HOST=0.0.0.0
      - FROM_EMAIL=vulkan@sumeetsaini.com
      - MAIL_ENABLED=false
      - CONTACT_EMAIL=dev-test@example.com
      - ETHEREAL_HOST=smtp.ethereal.email
      - ETHEREAL_PORT=587
      
  gateway:
    volumes:
      - ./services/gateway/sites/dev:/etc/nginx/conf.d:ro
