# Mailcow Dockerized Integration
include:
  - /opt/mailcow-dockerized/docker-compose.yml

networks:
  aether-network:
    external: true
  mailcow-network:
    external: true
    name: mailcowdockerized_mailcow-network