services:
  sumeetsaini_com:
    image: ghcr.io/kungfusaini/sumeetsaini_com:latest

  vulkan:
    image: ghcr.io/kungfusaini/vulkan:latest
    volumes:
      - ./services/vulkan/data:/app/data
      - vulkan_projects:/app/projects
      - vulkan_data_backup:/app/data-backup
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/secrets:/run/secrets
    environment:
      - NODE_ENV=prod
      - MAIL_ENABLED=true
      - MAILCOW_HOST=mailcowdockerized-postfix-mailcow-1
      - MAIN_EMAIL=${MAIN_EMAIL}
      - RELIQ_STUDIOS_EMAIL=${RELIQ_STUDIOS_EMAIL}
      - WELL_API_KEY=${WELL_API_KEY}
      - BACKUP_REPO_URL=https://github.com/kungfusaini/vulkan-data.git
      - GIT_AUTHOR_NAME=Vulkan Backup Bot
      - GIT_AUTHOR_EMAIL=backup@vulkan.sumeetsaini.com
      - VULKAN_GIT_TOKEN=${VULKAN_GIT_TOKEN}
      - PROJECTS_REPO_URL=${PROJECTS_REPO_URL}
      - PROJECTS_WEBHOOK_SECRET=${PROJECTS_WEBHOOK_SECRET}
      - PROJECTS_BASE_URL=https://vulkan.sumeetsaini.com
    networks:
      - aether-network
      - mailcowdockerized_mailcow-network

  arcanecodex:
    image: ghcr.io/kungfusaini/arcanecodex:latest
    networks:
      - aether-network

  ao3:
    image: ghcr.io/kungfusaini/ao3:latest
    networks:
      - aether-network

  reliqstudios:
    image: ghcr.io/kungfusaini/reliqstudios:latest
    networks:
      - aether-network

  reliqdigital:
    image: ghcr.io/kungfusaini/reliqdigital:latest
    networks:
      - aether-network

  bucketbot:
    image: ghcr.io/kungfusaini/bucketbot:latest
    container_name: bucketbot
    environment:
      - BUCKETBOT_TOKEN=${BUCKETBOT_TOKEN}
      - WELL_API_KEY=${WELL_API_KEY}
      - TELEGRAM_ID=${TELEGRAM_ID}
    networks:
      - aether-network
    restart: unless-stopped

  goblinbot:
    image: ghcr.io/kungfusaini/goblinbot:latest
    container_name: goblinbot
    environment:
      - GOBLINBOT_TOKEN=${GOBLINBOT_TOKEN}
      - WELL_API_KEY=${WELL_API_KEY}
      - TELEGRAM_ID=${TELEGRAM_ID}
    networks:
      - aether-network
    restart: unless-stopped

  gateway:
    image: ghcr.io/kungfusaini/gateway:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/letsencrypt:/var/www/letsencrypt:ro
    networks:
      - aether-network
      - mailcowdockerized_mailcow-network
    depends_on:
      - sumeetsaini_com
      - vulkan
      - arcanecodex
      - ao3
      - reliqstudios
      - reliqdigital
      - plausible

networks:
  aether-network:
    external: true
  mailcowdockerized_mailcow-network:
    external: true

volumes:
  vulkan_data_backup:
  vulkan_projects:


