# reliq.digital - Development
server {
    listen 80;
    server_name reliq.digital.localhost;

    location / {
        proxy_pass http://reliqdigital_dev/;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }
}