# Reliq Labs - Development
server {
    listen 80;
    server_name reliqlabs.localhost;

    location / {
        proxy_pass http://reliqlabs_dev/;
        include /etc/nginx/conf.d/common/proxy-headers.conf;
    }
}
