# Development Upstreams
upstream sumeetsaini_com_dev {
    server sumeetsaini_com:8080;
}

upstream vulkan_api_dev {
    server vulkan:3000;
}

upstream arcanecodex_dev {
    server arcanecodex:1313;
}

upstream ao3_dev {
    server ao3:80;
}

upstream reliqstudios_dev {
    server reliqstudios:1314;
}



