#!/usr/bin/env bash
# Add a domain to Mailcow end-to-end:
#   1. Create the domain (with a generous catchall budget)
#   2. Create one real mailbox <local>@<domain>
#   3. Create a catchall alias @<domain> -> <local>@<domain>
#   4. Generate a DKIM key (selector "dkim", 2048 bits)
#   5. Push the DKIM public key to Cloudflare as dkim._domainkey.<domain>
#
# Usage:
#   mailcow-add-domain.sh <domain> [--local me] [--name "Display Name"]
#                                  [--password STRING]   # else autogenerated
#
# Requires:
#   - jq, curl, openssl
#   - MAILCOW_API_KEY, MAILCOW_HOST, CF_API_TOKEN — set in the env or in
#     ~/.config/aether/env (sourced automatically).
#
# Outputs the generated mailbox password to stdout (only place it appears).

set -euo pipefail

# Load shared secrets / defaults.
if [[ -r "$HOME/.config/aether/env" ]]; then
    set -a; . "$HOME/.config/aether/env"; set +a
fi

DOMAIN=""
LOCAL="me"
DISPLAY_NAME=""
PASSWORD=""
MAILCOW_HOST="${MAILCOW_HOST:-mail.sumeetsaini.com}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --local)    LOCAL="$2"; shift 2 ;;
        --name)     DISPLAY_NAME="$2"; shift 2 ;;
        --password) PASSWORD="$2"; shift 2 ;;
        -h|--help)  sed -n '2,20p' "$0"; exit 0 ;;
        -*)         echo "unknown flag: $1" >&2; exit 1 ;;
        *)          DOMAIN="$1"; shift ;;
    esac
done

[[ -z "$DOMAIN" ]] && { echo "usage: $0 <domain> [--local me] [--name '...'] [--password ...]" >&2; exit 1; }
[[ -z "$DISPLAY_NAME" ]] && DISPLAY_NAME="$LOCAL"

MAILCOW_KEY="${MAILCOW_API_KEY:-}"
[[ -z "$MAILCOW_KEY" ]] && { echo "error: MAILCOW_API_KEY not set (put it in ~/.config/aether/env)" >&2; exit 1; }

CF_TOKEN="${CF_API_TOKEN:-}"
[[ -z "$CF_TOKEN" ]] && { echo "error: CF_API_TOKEN not set (put it in ~/.config/aether/env)" >&2; exit 1; }

if [[ -z "$PASSWORD" ]]; then
    PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
fi

MC="https://$MAILCOW_HOST/api/v1"
MC_AUTH=(-H "X-API-Key: $MAILCOW_KEY" -H "Content-Type: application/json")

mc() { curl -fsS "${MC_AUTH[@]}" "$@"; }

# Mailcow's API returns 200 with a JSON array of {type, msg} envelopes even on errors,
# so we have to look at .[0].type to know if a call actually succeeded.
# Sets LAST_RESULT to "created", "exists", or "error".
LAST_RESULT=""
mc_post() {
    local path="$1" body="$2" label="$3"
    local resp type msg
    resp="$(mc -X POST "$MC$path" --data "$body")"
    type="$(echo "$resp" | jq -r '.[0].type // .type // "unknown"')"
    msg="$(echo "$resp"  | jq -r '.[0].msg  // .msg  // "" | if type=="array" then join(" ") else . end')"
    case "$type" in
        success) echo "  + $label"; LAST_RESULT=created ;;
        danger|error)
            # mailcow uses "dkim_domain_or_sel_invalid" when a DKIM already exists for
            # that selector — treat it as "already exists" so the script stays idempotent.
            if [[ "$msg" == *"exists"* || "$msg" == *"already"* \
                || "$msg" == *"dkim_domain_or_sel_invalid"* \
                || "$msg" == *"is_alias_or_mailbox"* ]]; then
                echo "  = $label (already exists)"
                LAST_RESULT=exists
            else
                echo "  ! $label: $msg" >&2
                LAST_RESULT=error
                return 1
            fi ;;
        *) echo "  ? $label: $resp" >&2; LAST_RESULT=error ;;
    esac
}

echo "mailcow: $MAILCOW_HOST"
echo "domain:  $DOMAIN"
echo "mailbox: $LOCAL@$DOMAIN"

echo "adding domain..."
mc_post /add/domain "$(jq -nc --arg d "$DOMAIN" '{
    domain: $d, description: "", aliases: 400, mailboxes: 10,
    defquota: 3072, maxquota: 10240, quota: 10240,
    active: "1", rl_value: "", rl_frame: "s",
    backupmx: "0", relay_all_recipients: "0", restart_sogo: "1"
}')" "domain $DOMAIN"

echo "adding mailbox..."
mc_post /add/mailbox "$(jq -nc \
    --arg local "$LOCAL" --arg d "$DOMAIN" --arg n "$DISPLAY_NAME" --arg pw "$PASSWORD" '{
    local_part: $local, domain: $d, name: $n,
    quota: "3072",
    password: $pw, password2: $pw,
    active: "1", force_pw_update: "0",
    tls_enforce_in: "1", tls_enforce_out: "1"
}')" "mailbox $LOCAL@$DOMAIN"
MAILBOX_RESULT="$LAST_RESULT"

echo "adding catchall alias..."
mc_post /add/alias "$(jq -nc --arg d "$DOMAIN" --arg goto "$LOCAL@$DOMAIN" '{
    address: ("@" + $d), goto: $goto, active: "1", sogo_visible: "1"
}')" "@$DOMAIN -> $LOCAL@$DOMAIN"

echo "generating DKIM key..."
mc_post /add/dkim "$(jq -nc --arg d "$DOMAIN" '{
    domains: $d, dkim_selector: "dkim", key_size: 2048
}')" "DKIM key (selector=dkim, 2048)"

echo "fetching DKIM public key..."
DKIM_JSON="$(mc "$MC/get/dkim/$DOMAIN")"
DKIM_PUB="$(echo "$DKIM_JSON" | jq -r '.dkim_txt // .pubkey // empty')"
if [[ -z "$DKIM_PUB" ]]; then
    echo "error: could not read DKIM public key from mailcow response:" >&2
    echo "$DKIM_JSON" | jq . >&2
    exit 1
fi

# Mailcow returns the inner value (v=DKIM1;k=rsa;...). Cloudflare wants that, possibly
# chunked into 255-char strings inside quotes for long records — but the Cloudflare API
# accepts a single content string and handles chunking server-side.
DKIM_TXT_NAME="dkim._domainkey.$DOMAIN"

echo "pushing DKIM TXT to Cloudflare ($DKIM_TXT_NAME)..."
CF_API="https://api.cloudflare.com/client/v4"
CF_AUTH=(-H "Authorization: Bearer $CF_TOKEN" -H "Content-Type: application/json")
cf() { curl -fsS "${CF_AUTH[@]}" "$@"; }

ZONE_ID="$(cf "$CF_API/zones?name=$DOMAIN" | jq -r '.result[0].id // empty')"
[[ -z "$ZONE_ID" ]] && { echo "error: cloudflare zone $DOMAIN not found" >&2; exit 1; }

# Remove any existing TXT at dkim._domainkey OR placeholder at _domainkey
for n in "dkim._domainkey.$DOMAIN" "_domainkey.$DOMAIN"; do
    ids="$(cf "$CF_API/zones/$ZONE_ID/dns_records?type=TXT&name=$n&per_page=100" \
        | jq -r '.result[].id')"
    for id in $ids; do
        cf -X DELETE "$CF_API/zones/$ZONE_ID/dns_records/$id" >/dev/null
        echo "  - removed existing TXT $n"
    done
done

resp="$(cf -X POST "$CF_API/zones/$ZONE_ID/dns_records" --data "$(jq -nc \
    --arg n "$DKIM_TXT_NAME" --arg c "$DKIM_PUB" \
    '{type:"TXT",name:$n,content:$c,ttl:1,proxied:false}')")"
if [[ "$(echo "$resp" | jq -r .success)" == "true" ]]; then
    echo "  + TXT $DKIM_TXT_NAME"
else
    echo "  ! cloudflare DKIM push failed: $(echo "$resp" | jq -c .errors)" >&2
    echo "    DKIM record (add manually if needed):"
    echo "    $DKIM_TXT_NAME  TXT  $DKIM_PUB"
    exit 1
fi

echo
echo "done."
echo "================================================================"
echo "  mailbox:  $LOCAL@$DOMAIN"
if [[ "$MAILBOX_RESULT" == "created" ]]; then
    echo "  password: $PASSWORD"
    echo "  (save it — it is not stored anywhere else)"
else
    echo "  password: <unchanged; mailbox already existed>"
    echo "  to reset: pass --password ... and call /edit/mailbox, or use the SOGo UI"
fi
echo "  webmail:  https://$MAILCOW_HOST/SOGo/"
echo "  IMAP/SMTP host: $MAILCOW_HOST  (993 IMAPS, 465 SMTPS)"
echo "================================================================"
